<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGb3mGQD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGb3mGQD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGb3mGQD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGb3mGQD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGb3mGQD\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gb3mGQD',
    'container.build_id' => '4f9bfd05',
    'container.build_time' => 1582807750,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGb3mGQD');
