<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSEz9WgU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSEz9WgU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSEz9WgU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSEz9WgU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSEz9WgU\App_KernelDevDebugContainer([
    'container.build_hash' => 'SEz9WgU',
    'container.build_id' => '9d1b0990',
    'container.build_time' => 1583334105,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSEz9WgU');
