<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNBP0mol\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNBP0mol/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNBP0mol.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNBP0mol\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNBP0mol\App_KernelDevDebugContainer([
    'container.build_hash' => 'NBP0mol',
    'container.build_id' => 'ddcde88e',
    'container.build_time' => 1583240057,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNBP0mol');
