<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMGXKJiQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMGXKJiQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMGXKJiQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMGXKJiQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMGXKJiQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'MGXKJiQ',
    'container.build_id' => '14d715ab',
    'container.build_time' => 1583394081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMGXKJiQ');
